README.md
src/console.rs
src/lib.rs

Implemented [VirtIO console device](https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html#x1-2550003). This is useful in support for the second serial console in qemu.
Known Issues: no extra feature bit is supported. Only a single console is allowed.

Added virtio-console support.

---

src/blk.rs
src/lib.rs
src/queue.rs

Now VirtIOBlk device can be accessed in a non-blocking way based on IRQ, and we keep the interface compatible with the ecosystem which relies on this library since we did not change or remove any existing interface.
We only added 5 methods:
* `VirtIOBlk::read_block_nb`
* `VirtIOBlk::write_block_nb`
* `VirtIOBlk::pop_used`
* `VirtIOBlk::virt_queue_size`
* `VirtQueue::size`(only called by `VirtIOBlk::virt_queue_size`)
Their usage has been included in the code documentation.
1. Initialization: Call `virt_queue_size` to get the number of channels the caller should monitor on. Every descriptor in the descriptor table is called a channel. For example:
```rust
// condvars: BTreeMap<u16, Condvar>
let mut condvars = BTreeMap::new();
let channels = virtio_blk.exclusive_access().virt_queue_size(); …
```

IRQ-based VirtIOBlk access.

---

examples/riscv/src/main.rs
examples/riscv/src/virtio_impl.rs
src/lib.rs

This is neater and more hygenic, and available since Rust 2018.

Use macros individually.

---

examples/riscv/src/main.rs
examples/riscv/src/virtio_impl.rs
src/blk.rs
src/console.rs
src/gpu.rs
src/hal.rs
src/input.rs
src/lib.rs
src/net.rs
src/queue.rs

Rather than rely on `extern "C"` functions, this makes the HAL a trait that must be implemented and provided as a type parameter. This lets it be properly type checked and removes a bunch of `unsafe` blocks.

Use a safer approach to the HAL interface

---

.github/workflows/main.yml
src/hal.rs
src/hal/fake.rs
src/header.rs
src/queue.rs

I'd like to add tests for the device implementations too, but that's going to require some refactoring to allow the transport to be faked somehow.

Add tests for VirtQueue

---

examples/riscv/Makefile
examples/riscv/src/main.rs
src/blk.rs
src/console.rs
src/gpu.rs
src/hal.rs
src/input.rs
src/lib.rs
src/net.rs
src/queue.rs
src/transport/mmio.rs
src/transport/mod.rs

This PR makes a bunch of changes around the VirtIO transport implementation.
* I've added a new `Transport` trait. This currently only has one implementation (for the MMIO transport) but I plan to add a PCI implementation in a future PR.
* I've added support for the modern MMIO transport (version 2) in addition to the legacy one (version 1). Initially I did this as two separate implementations of `Transport`, but this turned out to be rather cumbersome to use so I've gone for a single implementation that stores the version and checks it as needed at runtime. This is only relevant during initialisation, so shouldn't have a significant runtime cost.
* As part of the above, I made the new `MmioTransport` wrap a `NonNull` pointer to the `VirtIOHeader` rather than having the caller create a …

Factor out trait for transport, and add support for modern MMIO transport

---

examples/riscv/src/main.rs
src/gpu.rs

Different versions of QEMU seem to have different default resolutions, so it was crashing due to an array access out of bounds.

Use actual GPU resolution in example rather than hardcoding.

---

Cargo.toml
src/blk.rs
src/console.rs
src/gpu.rs
src/input.rs
src/lib.rs
src/net.rs
src/queue.rs
src/transport/mmio.rs
src/volatile.rs

The way the `volatile` crate handles MMIO regions is not sound, because it creates references to memory which shouldn't be considered dereferenceable. There is an attempt to fix this in https://github.com/rust-osdev/volatile/pull/22 (and lots of discussion), but that PR has been open since May 2021 and doesn't seem near being submitted. Instead, I've implemented the functionality we need in a new `volatile` module here using the `addr_of!` and `addr_of_mut!` macros, keeping all MMIO regions as pointers and never creating references.
This works for the MMIO transport and config regions. For the Virtqueue, I don't think we need volatile access at all because it's just shared memory, not MMIO. We still shouldn't be using references, however, as DMA to these shared regions by the device …

Fix soundness issues with MMIO and shared memory

---

examples/riscv/Cargo.toml
examples/riscv/src/main.rs

It has a nicer API, and has a released crate rather than a git repository.

Use fdt crate rather than device_tree in riscv example.

---

src/transport/mod.rs

The VirtIO specification forbids this, and it prevents the device from working with crosvm's implementation.

Don't unset bits in the device status field.

---

examples/aarch64/src/hal.rs
examples/riscv/src/virtio_impl.rs
src/lib.rs

HAL implementations need to know it to know how much to allocate.

Expose PAGE_SIZE constant.

---

README.md
examples/aarch64/Makefile
examples/aarch64/src/main.rs
src/blk.rs
src/console.rs
src/gpu.rs
src/input.rs
src/lib.rs
src/net.rs
src/queue.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs
src/transport/pci/bus.rs

This is a fairly big PR, but I've tried to make the individual commits fairly logical and self-contained. Let me know if you'd prefer me to split it into several PRs.
Most of the code is in two new modules:
* `transport::pci::bus` contains the generic PCI part of it, mostly around accessing PCI configuration space via one of two possible CAMs.
* `transport::pci` contains the VirtIO-specific parts, primarily the `PciTransport` struct which implements the `Transport` trait.
I also fixed the device implementations to avoid non-volatile access to their VirtIO config regions, which was happening through the `Debug` implementations.
You can try the new implementation on aarch64 with `cd examples/aarch64/ && make qemu-pci`.

Add PCI transport

---

src/blk.rs
src/console.rs
src/gpu.rs
src/input.rs
src/lib.rs
src/net.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs

At least in the case of the PCI transport, the device says how big its configuration space is. We should check that it is at least as big as we expect, and return an error if not, to avoid possible out of bounds accesses.
This PR also reduces the alignment requirement for device config space from 8 bytes to 4 bytes, to match what the VirtIO specification allows.

Check size of config space

---

src/blk.rs
src/console.rs
src/gpu.rs
src/input.rs
src/net.rs
src/queue.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs

Otherwise the device might continue accessing them, despite the DMA memory having been deallocated, i.e. a use-after-free.

Reset queues when device is dropped.

---

src/blk.rs
src/console.rs
src/gpu.rs
src/input.rs
src/net.rs
src/queue.rs

`Queue::add` must be marked as unsafe, because the caller must ensure that the input and output buffers remain valid until device has finished using them. I've added a helper method `Queue::add_notify_wait_pop` to handle the blocking case safely. This doesn't return until the matching token has been popped from the queue.

Fix soundness issues with VirtQueue

---

src/console.rs
src/gpu.rs
src/hal.rs
src/net.rs
src/queue.rs

Clippy doesn't like all-caps type or enum variant names, or unnecessary casts.

Fix some clippy warnings.

---

Cargo.toml
src/blk.rs
src/gpu.rs
src/input.rs
src/lib.rs
src/net.rs
src/volatile.rs

The derive macros in `zerocopy` check that the structs are actually valid convert to and from bytes. This required converting some enums to structs, as there's no guarantee that the value we get is actually a valid enum variant.

Use zerocopy rather than our AsBuf trait.

---

src/blk.rs
src/lib.rs

Pass request buffer into `read_block_nb` and `write_block_nb` rather than allocating it on the stack, so that it can be kept around until the request completes.
This fixes bug #7.

Improve non-blocking API of VirtIOBlk and add documentation.

---

examples/aarch64/Makefile
examples/aarch64/src/main.rs
src/console.rs

* Added a method to get information such as the number of rows and columns.
* Keep track of the token of the outstanding receive request, and ensure there is never more than one.
* Check whether the request has completed at the start of `recv` as well as in `ack_interrupt`, in case the client is not using interrupts.
* Added some more documentation.
* Added a test in the aarch64 example.

Improve VirtIOConsole

---

src/blk.rs
src/lib.rs
src/queue.rs
src/transport/pci.rs

This is a more accurate description of the issue.

Rename Error::BufferTooSmall to QueueFull and improve documentation.

---

examples/aarch64/.cargo/config
examples/aarch64/Makefile
examples/aarch64/build.rs
examples/aarch64/crosvm.ld
examples/aarch64/idmap_crosvm.S
examples/aarch64/image.ld
examples/aarch64/qemu.ld
examples/aarch64/src/logger.rs
examples/aarch64/src/main.rs
examples/aarch64/src/uart8250.rs

crosvm behaves a bit differently to QEMU so it is useful to test under both.
Unfortunately we need a different memory layout, which means a different linker script and idmap.

Add support for running aarch64 example under crosvm

---

examples/aarch64/src/hal.rs
examples/riscv/src/virtio_impl.rs
src/device/blk.rs
src/device/console.rs
src/device/input.rs
src/hal.rs
src/hal/fake.rs
src/lib.rs
src/queue.rs

These are necessary on platforms where devices don't have access to all memory of the VM, such as if the device is behind an IOMMU or the VM memory isn't exposed to the host.

Add methods to Hal to share and unshare buffers with device

---

README.md

I accidentally copy-pasted too much, whoops.

Fix links in README.

---

examples/aarch64/src/hal.rs
examples/riscv/src/virtio_impl.rs
src/device/console.rs
src/device/gpu.rs
src/hal.rs
src/hal/fake.rs
src/queue.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs

Only the legacy MMIO transport requires the three parts of the virtqueue to be contiguous. In other cases we can allocate the regions written by the driver separately from the region written by the device. This will allow systems with an IOMMU or equivalent to prevent the device from writing to regions which it shouldn't, such as the descriptor table and available ring.
This also reduces the size of the contiguous region allocated, which may reduce memory fragmentation.

Specify direction when allocating DMA regions

---

src/transport/pci.rs

(Writing 0 to QueueReady with MMIO transport is, however.)

Writing 0 to queue_enable for PCI transport isn't allowed.

---

src/device/blk.rs
src/lib.rs

* Convert different response statuses from device to different `Error` variants rather than converting them all to `Error::IoError`.
* Return the same errors from `complete_read_block` and `complete_write_block` as from the blocking versions, for consistency.

Improve error reporting of VirtIOBlk

---

src/device/console.rs
src/device/gpu.rs
src/hal.rs
src/lib.rs
src/queue.rs
src/transport/pci.rs

Miscellaneous cleanups around the `Dma` struct and how it is used.

Clean up Dma

---

src/device/blk.rs
src/device/console.rs
src/device/input.rs
src/queue.rs

The `VirtIOConsole` and `VirtIOInput` drivers weren't sending available buffer notifications to the device like they should, so I've fixed that. I've also implemented support for the device to suppress available buffer notifications using the flags on the used ring.

Support available buffer notification suppression, and send notifications for console and input

---

src/lib.rs

This makes it easier for clients of the library to display meaningful error messages.

Implement Display for Error.

---

examples/aarch64/src/hal.rs
examples/riscv/src/virtio_impl.rs
src/hal.rs
src/hal/fake.rs
src/lib.rs
src/queue.rs
src/transport/fake.rs
src/transport/pci.rs

The main goal of this change is to allow the `Hal` implementation to validate that the MMIO regions reported by a VirtIO device using the PCI transport is actually within the range expected by the OS. This prevents a malicious device from using bogus BARs to trick the driver into reading or writing arbitrary memory. This is important in a VM which doesn't trust its host, such as under pKVM.
`Hal::phys_to_virt` was previously being used for two different cases: for converting the physical addresses of DMA regions allocated by `Hal::dma_alloc` to virtual addresses, and for the MMIO addresses mentioned above. This PR removes the first use-case by having `Hal::dma_alloc` instead return both physical and virtual addresses for the allocated region. I've also added the virtual address as a …

Allow HAL to validate MMIO ranges

---

src/transport/mmio.rs
src/transport/pci.rs

Otherwise the driver will fail to initialise it next time, as the queues will already be set.

Reset device when the transport is dropped.

---

examples/aarch64/src/hal.rs
examples/riscv/src/virtio_impl.rs
src/device/blk.rs
src/device/console.rs
src/device/gpu.rs
src/device/input.rs
src/device/net.rs
src/hal.rs
src/hal/fake.rs
src/queue.rs
src/transport/pci.rs

The `Hal` trait should be marked as unsafe, as implementations need to return valid pointers from `dma_alloc` and `mmio_phys_to_virt` to avoid undefined behaviour in the drivers. Most of the functions in it (all except `dma_alloc`) should also be marked as unsafe, because the caller needs to pass valid pointers or addresses to avoid undefined behaviour in the HAL implementation. I've added comments explaining the requirements on each side.
I've also improved the safety comments in `queue.rs`, and changed various methods to take buffers by reference rather than pointer. This doesn't make them safe (except for `add_notify_wait_pop`, which I think actually is now), but reduces the safety requirements we need to document somewhat, as we can at least assume that a reference is non-null and is …

Mark parts of the `Hal` trait unsafe

---

src/device/console.rs

Since the `receive_token` was never reset, the virtio console device would only ever add one request. All future calls to `poll_retrieve` would do nothing.

Allow Virtio Console driver to support multiple read requests

---

examples/aarch64/src/main.rs
examples/riscv/Cargo.toml
examples/riscv/Makefile
examples/riscv/src/main.rs
examples/riscv/src/tcp.rs
src/device/input.rs
src/device/mod.rs
src/device/net.rs

Main changes:
* Using the following APIs to receive/transmit packets:
+ receive: call `receive()` to pop a `RxBuffer` from the NIC queue, process its data, and then call `recycle_rx_buffer()` to add it back to the NIC queue.
+ transmit: call `new_tx_buffer()` to allocate a `TxBuffer`, fill it with data, and then call `send()` to transmit it.
* Pre-allocate `RxBuffer`s to fill the NIC queue on initialization.
* Add an example using [smoltcp](https://github.com/smoltcp-rs/smoltcp) that implements a simple echo server.

Refactor virtio network device APIs to improve driver performance

---

src/device/net.rs

Reduce the number of casts, and use the `checked_sub` method rather than checking manually.

Minor cleanups in network driver

---

examples/aarch64/src/main.rs
src/device/socket/mod.rs
src/device/socket/vsock.rs

Methods to connect, request credit and so on won't block until the other end responds to them, but rather will return immediately. The client should then call `poll_recv`, which will return one of several possible events either for data being received on the connection, or connection, disconnection. It can do this interleaved with whatever other operations it needs to do rather than blocking indefinitely on the vsock.
This also lays the groundwork for handling more than one connection at once, in which case events for different connections will be interleaved arbitrarily.
I've added some blocking helpers `wait_for_connect` and `wait_for_recv` to give something similar to the old behaviour, but these won't work with multiple connections.

Change vsock driver to poll model

---

src/queue.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs

1. No queue is selected when read `Transport::max_queue_size()`.
3. Device is not reset in `Transport::begin_init()`.

Fix some bugs

---

README.md
examples/x86_64/.cargo/config
examples/x86_64/Cargo.toml
examples/x86_64/Makefile
examples/x86_64/linker.ld
examples/x86_64/src/boot.rs
examples/x86_64/src/hal.rs
examples/x86_64/src/heap.rs
examples/x86_64/src/logger.rs
examples/x86_64/src/main.rs
examples/x86_64/src/multiboot.S
examples/x86_64/src/tcp.rs
examples/x86_64/src/trap.rs

Add x86_64 example using virtio PCI devices:
- virtio-gpu-pci
- virtio-blk-pci
- virtio-net-pci
Currently the PCI ECAM base (MMCONFIG) is hardcoded to `0xB000_0000`.

Add x86_64 example using virtio PCI devices

---

src/hal.rs

`VirtQueue` was assuming this but it wasn't documented. If the pages are not zeroed then the driver won't behave as expected.

Document that Hal::dma_alloc must zero pages.

---

Cargo.toml
src/device/console.rs
src/device/gpu.rs
src/device/mod.rs
src/device/socket/mod.rs
src/device/socket/vsock.rs
src/lib.rs

Several device drivers were using `Dma::new` to allocate internal buffers which they then added to virtqueues. However, `VirtQueue::add` already takes care of sharing buffers with the device by calling `Hal::share`, which may copy the contents of the buffer to a DMA region if necessary, so the original buffer doesn't need to be allocated as a DMA buffer. In fact this may be a security issue in protected VMs, as the original buffer is shared with the host unnecessarily.
Instead, the internal buffers can just be allocated from the heap as usual.
This adds a dependency on `alloc` to the vsock, GPU and console drivers. If this is a problem then I could instead add a method to `Hal` to allocate a non-DMA buffer, but I think in practice most users of this crate will have `alloc` anyway.

Use heap rather than DMA buffer for buffers which will be added to queues

---

examples/aarch64/src/main.rs
src/device/socket/mod.rs
src/device/socket/vsock.rs

In particular:
* Changed the `VirtIOSocket::connect` method to take a `VsockAddr` rather than separate CID and port. The `VsockAddr` was already used in `VsockEvent` so this is more consistent.
* `VirtIOSocket::new` to allocate buffers for the RX virtqueue individually rather than allocating one big buffer and splitting it. This makes the code a bit simpler, and also may make allocation easier as the allocator doesn't have to find such a large contiguous memory range.
* Added `VirtIOSocket::guest_cid` method to get the CID assigned to the VM.

Minor improvements to vsock driver

---

examples/aarch64/src/main.rs
src/device/socket/mod.rs
src/device/socket/multiconnectionmanager.rs
src/device/socket/singleconnectionmanager.rs
src/device/socket/vsock.rs

This patch series starts by splitting out the connection management functionality of `VirtIOSocket` into a separate `SingleConnectionManager` which maintains the existing functionality. It then adds a more complex `VsockConnectionManager` which can handle multiple simultaneous connections, including incoming connections. `VsockConnectionManager` maintains per-connection ring buffers internally rather than copying directly from the virtqueue buffer to the client buffer as `SingleConnectionManager` does. This means an extra copying step, but allows it to implement credit properly and handle credit requests automatically. It also keeps track of which ports the guest is listening on, and automatically accepts connections on them while rejecting incoming connections on any other ports.

Support multiple and incoming connections in vsock driver

---

Cargo.toml
src/hal/fake.rs

This helps ensure in tests that drivers aren't sharing with the wrong direction or forgetting to unshare. Drivers (or queue implementations) which do this would pass tests but fail to work properly when used with a HAL implementation which actually requires sharing and unsharing buffers with the device.

Copy data back and forth to new buffer in fake HAL share.

---

src/device/blk.rs

This is part of an attempt at splitting #96 into more manageable chunks to review.
These features are fairly straightforward, and don't change anything about memory management or queue structure.

Add support for flushing block devices and getting their IDs

---

src/device/net.rs
src/device/socket/vsock.rs
src/hal.rs
src/hal/fake.rs
src/queue.rs

The vsock driver was doing this, which caused problems with the HAL implementation trying to share an empty region of memory.

Avoid adding empty buffers to queue

---

README.md
src/device/blk.rs
src/device/console.rs
src/device/gpu.rs
src/device/input.rs
src/device/net.rs
src/device/socket/vsock.rs
src/queue.rs

This is based on some of the work in #96, but fixes some issues there with how allocation and DMA memory is handled, adds tests for the indirect virtqueue itself, and also adds support to the fake device support so that device tests will work with indirect queues.
Devices can choose when constructing a `VirtQueue` whether it should support indirect descriptors or not, based on their preference and the device features. For now only the `VirtIOBlk` driver uses indirect descriptors (if the underlying device supports it). If a `VirtQueue` is constructed with indirect descriptor support then it will use them whenever more than one buffer is added to the queue. There's no point using indirect descriptors for a single buffer so we don't bother.
Space for the indirect descriptor lists is …

Add support for indirect descriptors in VirtQueue with alloc feature

---

examples/aarch64/src/main.rs
examples/riscv/src/main.rs
examples/x86_64/src/main.rs
src/device/blk.rs

The VirtIO block device specification allows more than one block to be read or written at a time, so there's no reason to limit our implementation to a single block.
I've kept it to just a single buffer for all blocks. Supporting multiple buffers in the same request would require either allocation, or maybe somehow refactoring `VirtQueue::add_notify_wait_pop` to take iterators for the buffers rather than slices.

Support reading or writing more than one block at once.

---

README.md
src/device/blk.rs
src/device/console.rs
src/device/gpu.rs
src/device/input.rs
src/device/net.rs
src/device/socket/vsock.rs
src/queue.rs
src/transport/mod.rs

Another feature broken out of #96. I've also simplified `Transport::begin_init` to just take a set of supported features rather than a closure.

Add support for VIRTIO_F_EVENT_IDX buffer notification suppression.

---

examples/aarch64/src/main.rs
src/device/socket/connectionmanager.rs

This PR addresses a bug in the vsock connection manager. Prior to the PR, the guest doesn't update the host after it processes the local buffer. As a result, when the receiving message length reaches the buffer capacity, the host could mistakenly stop sending the message, unaware that the guest still had available buffer.
This fix ensures that the credit is correctly updated after processing the local buffer, allowing for continuous message transmission between the host and the guest.

[vsock] Add method to send credit update manually

---

src/device/socket/connectionmanager.rs

The status of the used receive buffer is more helpful for users when configuring credit updates.

Change the function to retrieve used buffer instead of available buffer

---

src/device/socket/connectionmanager.rs

This avoids using the same name as recv_buffer_available_bytes.

Rename RingBuffer#available to free.

---

.github/workflows/main.yml
examples/aarch64/rust-toolchain.toml
examples/riscv/Makefile
examples/riscv/rust-toolchain
examples/riscv/rust-toolchain.toml
examples/riscv/src/tcp.rs
examples/x86_64/Makefile
examples/x86_64/rust-toolchain
examples/x86_64/rust-toolchain.toml
examples/x86_64/src/tcp.rs
rust-toolchain.toml

When I was testing the x86_64 example with `tcp` feature, I got a compilation error at the line of `dev.transmit(tx_buf).unwrap();`.
The error was introduced in a recent PR: https://github.com/rcore-os/virtio-drivers/pull/111.
It was overlooked by CI because the default value `tcp=off` was in effect.
I found the original rationale for disabling `tcp` in CI from this commit message: https://github.com/rcore-os/virtio-drivers/pull/86/commits/5b0786b09ec94840ad181818be72ba62d217dee0
>Disable tcp feature in x86_64 example by default.
> It waits forever, which is no good in CI.
So I modify the `test_echo_server` function to break out the dead loop.
I also applied the same fix to the riscv example.

ci: turn on tcp feature in examples

---

src/queue.rs

We need to update `used_event` to support `VIRTIO_F_EVENT_IDX` feature.
REF: https://elixir.bootlin.com/linux/latest/source/drivers/virtio/virtio_ring.c#L870

Bug fix: update VirtQueue.avail.used_event to support VIRTIO_F_EVENT_IDX

---

src/queue.rs

This is necessary to correctly synchronise with the host. The previous fences were not correct.
Fixes #125.

Use atomic reads and writes for available and used ring.

---

src/device/console.rs
src/device/input.rs
src/device/socket/vsock.rs
src/hal.rs
src/queue.rs
src/transport/mmio.rs
src/transport/pci.rs
src/transport/pci/bus.rs

None of these types are bound to any particular thread, and there is no interior mutability; they use `&mut self` for any methods that change state.
Note that `Send` and `Sync` are automatically derived for some device types, e.g. `VirtIOBlk` and `VirtIOGpu`, so we don't need explicit implementations for them.

Implement Send and Sync for various types.

---

src/queue.rs

Emit a compile-time error if a queue size is invalid, instead of a runtime error. This allows catching mistakes earlier, since the queue size is always defined at compile time.
Unfortunately this means we must remove the corresponding test, as the only way to test a compile-time failure (without using external crates) is via doctests, which do not have access to private items (which is the case for `VirtQueue`).

queue: check queue size at compile time

---

src/device/socket/connectionmanager.rs
src/device/socket/protocol.rs
src/device/socket/vsock.rs

Linux seems to require both send and receive shutdown hints before it will acknowledge the shutdown, so set both by default.

 Allow vsock stream shutdown hints to be specified

---

src/queue.rs

Noticed this while investigating #135.

Panic if buffer length >= 4 GiB, rather than passing an incorrect length

---

src/device/console.rs
src/device/gpu.rs
src/device/input.rs
src/device/net/dev_raw.rs
src/device/net/mod.rs
src/device/socket/vsock.rs

They were originally only added for block devices, but there's no reason to limit them to that.

Support indirect descriptors in all drivers.

---

src/device/socket/mod.rs
src/device/socket/vsock.rs

Some of the types used in methods on `VirtIOSocket` were private, despite the methods being part of the crate's public API. They should also be public so that people can use the methods.

Make types needed to use `VirtIOSocket` public.

---

src/device/input.rs
src/device/net/mod.rs
src/lib.rs
src/volatile.rs

Rather than just adding bytes to a buffer, these return the appropriate type for the selector.
The size of the data available for a particular selector is given by the device, so only read that much data rather than the full 128 bytes every time.

Add typed getters for input device config space

---

src/device/socket/vsock.rs

After the `VirtIOSocket` supports custom `RX_BUFFER_SIZE`s, we need to update the `Send` and `Sync` impls such that `VirtIOSocket`s with custom buffer sizes work the same as those using the default buffer sizes.

Update Send and Sync impls for VirtIOSocket

---

examples/aarch64/Cargo.toml
examples/aarch64/Makefile
examples/aarch64/src/main.rs
examples/riscv/Cargo.toml
examples/riscv/src/main.rs

The `fdt` crate hasn't been updated in a while, `flat_device_tree` is a fork with an improved API. I also fixed a bug which got the prefetchable attribute for PCI ranges from the wrong bit.

Use `flat_device_tree` crate for examples

---

examples/aarch64/src/main.rs
examples/riscv/src/tcp.rs
examples/x86_64/src/tcp.rs
src/device/console.rs

I've replaced the `info` method with a new method `size`, which properly checks the supported features before reading the config space. There wasn't much point reading `max_ports` when the driver doesn't support multiple ports anyway.

Support size and emergency write features on VirtIOConsole

---

Cargo.toml
src/device/socket/error.rs
src/lib.rs
src/transport/mmio.rs
src/transport/pci.rs
src/transport/pci/bus.rs

This reduces boilerplate, and adds a core::error::Error implementation.

Use thiserror for error types.

---

examples/aarch64/src/main.rs
examples/x86_64/src/main.rs
src/transport/pci.rs
src/transport/pci/bus.rs

This will allow implementations using methods other than MMIO to be implemented outside of this crate.

Factor configuration access out from PciRoot to a new trait.

---

examples/aarch64/src/main.rs
src/device/blk.rs
src/device/console.rs
src/device/gpu.rs
src/device/input.rs
src/device/net/dev_raw.rs
src/device/net/mod.rs
src/device/socket/vsock.rs
src/device/sound.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs

The config space is not necessarily memory mapped, some other transports require the config space to be accessed via other IO operations such as hypercalls.

Add methods to Transport to read and write config space, rather than returning a pointer.

---

src/transport/mod.rs
src/transport/some.rs

This lets clients write code that works for a VirtIO device with either transport without generics. Dynamic dispatch isn't possible because `Transport` isn't object-safe.

Add SomeTransport, an enum wrapping either an MMIO or PCI transport.

---

examples/aarch64/src/main.rs
examples/riscv/src/main.rs
examples/x86_64/Cargo.toml
src/lib.rs
src/queue.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs
src/transport/some.rs

Also some other minor transport-related cleanups suggested by @fkm3 on #163.

Check bounds of config space for MMIO transport

---

src/lib.rs
src/queue.rs
src/transport/fake.rs
src/transport/pci.rs
src/transport/pci/bus.rs
src/volatile.rs

Also added Rustdoc comments for fake transport, as it was breaking the build. Not sure why this wasn't an issue before.

Use &raw rather than addr_of macros

---

src/transport/mod.rs
src/transport/pci.rs
src/transport/some.rs
src/transport/x86_64.rs
src/transport/x86_64/cam.rs
src/transport/x86_64/hypercalls.rs

VMs running under pKVM on x86-64 cannot do MMIO, so a hypercall based transport is provided instead.

Add hypercall-based PCI CAM and transport for x86-64 pKVM.

---

examples/aarch64/src/logger.rs

Actually initialize the uart to silence all the "PL011 data written to disabled UART" guest errors from QEMU.
Signed-off-by: Manos Pitsidianakis <manos.pitsidianakis@linaro.org>

examples/aarch64: initialize uart device

---

src/device/console.rs
src/device/input.rs
src/device/net/dev.rs
src/hal.rs
src/queue.rs
src/queue/owning.rs
src/transport/mmio.rs
src/transport/pci.rs
src/transport/pci/bus.rs

Most of the `unsafe` blocks already have safety comments, but they were in a non-standard `// Safe because` format that `clippy::undocumented_unsafe_blocks` doesn't understand, rather than `// SAFETY:` comments.  This just switches them so that `clippy` understands them and can check them with `#![deny(clippy::undocumented_unsafe_blocks)]`.  This brings down the number of undocumented `unsafe`s, according to `clippy` and excluding `#[cfg(test)]` code, from 69 to 15.

Change `// Safe because` comments to proper `// SAFETY:` comments `clippy` recognizes

---

examples/aarch64/src/main.rs
src/transport/pci.rs
src/transport/pci/bus.rs
src/transport/x86_64.rs

64-bit memory BARs not only have a 64-bit-wide address, but also a 64-bit-wide size. Change the bar_info() function to retrieve the upper 32 bits of the size and include it in the size calculation.
This modifies the return type of the BarInfo::memory_address_size() function, so callers may need to modify their code to adapt to the new 64-bit size.
Fixes GitHub issue #177.

PCI: read full 64-bit size of 64-bit memory BARs

---

src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs
src/transport/x86_64.rs

Clean up the API by making invalid device types unrepresentable; APIs that need to represent a potentially failed conversion should use Option or Result instead.
The MMIO transport is modified slightly to read the device ID up front (like the PCI transport).
This also makes it impossible to construct a Transport instance for an unknown/unsupported DeviceType, which seems like a reasonable trade-off to me; it would also be possible to support such a scenario by making Transport::device_type() return Option<DeviceType> instead, but that would make the API clunkier to use.

Remove DeviceType::Invalid and make conversion fallible

---

src/device/gpu.rs
src/device/sound.rs
src/lib.rs
src/queue.rs
src/transport/x86_64/hypercalls.rs

Add `SAFETY` comments to the remaining undocumented `unsafe` blocks. I did my best to accurately cover why each block is unsafe, but I'm not familiar with virtio and may have missed some subtle details. Let me know if anything needs adjustment.

Add remaining safety comments

---

README.md
examples/aarch64/Makefile
examples/aarch64/src/main.rs
examples/riscv/Makefile
examples/riscv/src/main.rs
examples/x86_64/Makefile
examples/x86_64/src/main.rs
src/device/mod.rs
src/device/rng.rs

Add a driver for the entropy source device, also known as virtio-rng in qemu. Add basic usage as well in the repo examples for all architectures.

Add VirtIORng driver

---

.github/workflows/main.yml

If they don't finish after a minute they are going to hang forever.

Reduce timeout for running examples.

---

src/device/blk.rs
src/device/console.rs
src/device/gpu.rs
src/device/input.rs
src/device/net/dev.rs
src/device/net/dev_raw.rs
src/device/rng.rs
src/device/sound.rs
src/transport/fake.rs
src/transport/mmio.rs
src/transport/mod.rs
src/transport/pci.rs
src/transport/some.rs
src/transport/x86_64.rs

This appears to be a known limitation in the current implementation. Without this change, interrupt service routines are unable to tell why they are running (is there a new virtqueue packet to process or did the device confirmation change).
This PR also makes a tiny cleanup change to remove a safety comment that is no longer needed.

Make `ack_interrupt` return interrupt status
